In [2]:
import numpy as np
import pandas as pd


from aeon.transformations.collection.convolution_based import Rocket, MiniRocket
from sklearn.linear_model import RidgeClassifierCV

from utils import config
from utils.utils import transform_series, dimensions_fusion, load_dataset, PAA

In [3]:
RESULTS_FILENAME = f'results_final.csv'

In [4]:
try:
    df_results = pd.read_csv(f"{config.RESULTS_FOLDER}/{RESULTS_FILENAME}")
except FileNotFoundError:
    df_results = pd.DataFrame(columns=[
        "dataset",
        "representation",
        "operation",
        "accuracy",
        "convolution_algorithm",
        "classification_algorithm",
    ])


In [5]:
from aeon.datasets import load_from_ts_file, load_classification

dataset_name = "LSST"
representation = "CWT"
operation = "sum"

dataset = load_dataset(dataset_name, config.DATASETS_FOLDER)

X_train, y_train = load_from_ts_file(f"{config.DATASETS_FOLDER}/{dataset_name}/{dataset_name}_TRAIN.ts")
X_test, y_test = load_from_ts_file(f"{config.DATASETS_FOLDER}/{dataset_name}/{dataset_name}_TEST.ts")

# X_train, y_train = load_classification(dataset_name, split="Train")
# X_test, y_test = load_classification(dataset_name, split="Test")




X_train = dataset["X_train"]
y_train = dataset["y_train"]
X_test = dataset["X_test"]
y_test = dataset["y_test"]



In [9]:
series = X_train[0][0]

In [14]:
series

array([  17.597  ,    0.22974,  -29.654  ,  -59.21   ,  -72.064  ,
        -58.355  ,  -24.086  ,    9.5313 ,   19.02   ,   -3.35   ,
        -40.648  ,  -61.347  ,  -43.567  ,    4.9636 ,   49.192  ,
         52.197  ,    4.6215 ,  -66.308  , -116.57   , -118.12   ,
        -77.84   ,  -28.137  ,    0.75407,    2.2877 ,   -7.7249 ,
        -10.118  ,    0.80155,   17.232  ,   31.031  ,   43.985  ,
         64.09   ,   92.687  ,  117.42   ,  119.82   ,   91.591  ,
         43.719  ])

In [16]:
# 
series = X_train[0][0]

series_transformed = transform_series(series, "CWT")

fusioned_series = dusion_


In [17]:
something.flatten()

array([ 1.54545455,  1.12680094, -0.1171813 , ...,  1.02373224,
        0.56935552,  1.54545455])

In [6]:
series_length = min([min([len(dimension) for dimension in case]) for case in X_train])
a = []
for case in X_train:
    s = []
    for series in case:
        p = PAA(series, series_length)
        s.append(p)
    a.append(np.array(s))
X_train = a

# print(X_train.shape)

#series_length = int(mean([mean([len(dimension) for dimension in case]) for case in X_test]))
series_length = min([min([len(dimension) for dimension in case]) for case in X_test])
b = []
for case in X_test:
    s = []
    for series in case:
        ar = []
        p = PAA(series, series_length)
        s.append(p)
    b.append(s)
X_test = b


In [10]:



print(np.array(X_train).shape)
print(y_train.shape)

print(
    len(PAA(np.array(X_train)[0][0], 10))
)


(128, 6, 17984)
(128,)
10


In [16]:
something = transform_series(X_train[0][0], "RP")
PAA(something.flatten(), 300)

array([0.5 , 0.25, 0.5 , 0.4 , 0.  , 0.5 , 0.6 , 0.  , 0.5 , 0.  , 0.75,
       0.25, 0.2 , 0.5 , 1.  , 0.  , 0.  , 0.25, 0.2 , 0.5 , 0.  , 0.2 ,
       0.5 , 0.  , 0.  , 0.25, 0.5 , 0.5 , 0.2 , 0.5 , 0.  , 0.  , 0.  ,
       0.  , 0.6 , 0.  , 0.25, 0.2 , 0.25, 0.  , 0.  , 0.  , 0.5 , 0.2 ,
       0.75, 0.25, 0.2 , 0.  , 0.  , 0.  , 0.25, 0.25, 0.5 , 0.2 , 0.  ,
       0.5 , 0.2 , 0.  , 0.5 , 0.  , 0.75, 0.25, 0.2 , 0.5 , 1.  , 0.2 ,
       0.25, 0.25, 0.6 , 0.25, 0.25, 0.2 , 0.5 , 0.5 , 0.  , 0.5 , 0.5 ,
       0.5 , 0.4 , 0.  , 0.75, 0.6 , 0.  , 0.  , 0.8 , 0.25, 0.5 , 0.  ,
       0.25, 0.  , 0.  , 0.  , 0.5 , 0.2 , 0.75, 0.25, 0.2 , 0.  , 0.  ,
       0.  , 0.5 , 0.5 , 0.5 , 0.2 , 0.25, 0.25, 0.  , 0.  , 0.5 , 0.  ,
       0.75, 0.25, 0.2 , 0.5 , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.5 ,
       0.  , 0.  , 0.75, 0.2 , 0.  , 0.  , 0.  , 0.4 , 0.  , 0.  , 0.4 ,
       0.25, 0.75, 0.  , 0.75, 0.25, 0.2 , 0.5 , 1.  , 0.  , 0.  , 0.5 ,
       0.2 , 0.5 , 0.25, 0.2 , 0.  , 0.  , 0.  , 0.

In [8]:
transformed_train_series = []
for exemple in X_train[:2]:
    exemple_processed = []
    for series in exemple:
        try:
            t = transform_series(series, "CWT")
            exemple_processed.append(t.flatten())
        except:
            print(series)
    transformed_train_series.append(exemple_processed)
transformed_test_series = []
# for exemple in X_test:
#     exemple_processed= []
#     for series in exemple:
#         try:
#             t = transform_series(series, "CWT")
#             exemple_processed.append(t.flatten())
#         except:
#             print(series)
#     transformed_test_series.append(exemple_processed)


In [9]:
print(np.array(transformed_train_series).shape)
print(y_train.shape)


(2, 200, 400)
(25000,)


In [10]:
X_train_transformed = dimensions_fusion(transformed_train_series, operation)
X_test_transformed = dimensions_fusion(transformed_test_series, operation)


In [11]:
print(X_train_transformed.shape)
print(len(y_train))

(2, 400)
25000


In [13]:
classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10))
classifier.fit(X_train_transformed, y_train)

accuracy = classifier.score(X_test_transformed, y_test)

new_result_line = {
    "dataset": dataset_name,
    "representation": representation,
    "operation": operation,
    "accuracy": accuracy,
    "convolution_algorithm": None,
    "classification_algorithm": "Ridge",
}
df_results.loc[len(df_results)] = new_result_line
df_results.to_csv(f"{config.RESULTS_FOLDER}/{RESULTS_FILENAME}", index=False)


ValueError: Input X contains NaN.
RidgeClassifierCV does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
algorithm = Rocket(n_kernels=10000, n_jobs=-1, random_state=6)
algorithm.fit(X_train_transformed)

X_train_transformed = algorithm.transform(X_train_transformed)
X_test_transformed = algorithm.transform(X_test_transformed)

classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10))
classifier.fit(X_train_transformed, y_train)

accuracy = classifier.score(X_test_transformed, y_test)

new_result_line = {
    "dataset": dataset_name,
    "representation": representation,
    "operation": operation,
    "accuracy": accuracy,
    "convolution_algorithm": "Rocket",
    "classification_algorithm": "Ridge",
}
df_results.loc[len(df_results)] = new_result_line
df_results.to_csv(f"{config.RESULTS_FOLDER}/{RESULTS_FILENAME}", index=False)


In [ ]:
algorithm = MiniRocket(n_kernels=10000, n_jobs=-1, random_state=6)
algorithm.fit(X_train_transformed)

X_train_transformed = algorithm.transform(X_train_transformed)
X_test_transformed = algorithm.transform(X_test_transformed)

classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10))
classifier.fit(X_train_transformed, y_train)

accuracy = classifier.score(X_test_transformed, y_test)

new_result_line = {
    "dataset": dataset_name,
    "representation": representation,
    "operation": operation,
    "accuracy": accuracy,
    "convolution_algorithm": "MiniRocket",
    "classification_algorithm": "Ridge",
}
df_results.loc[len(df_results)] = new_result_line
df_results.to_csv(f"{config.RESULTS_FOLDER}/{RESULTS_FILENAME}", index=False)
